server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.32:3306/cloud2020?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Gaojingjian@123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #配置个别名，这样可以直接定位
  type-aliases-package: com.diana.springcloud.entities
#  datasource:
#    url: jdbc:mysql://192.168.1.32:3306/cloud2020?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: Gaojingjian@123

